// <auto-generated />
using System;
using BibWpf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BibWpf.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BibWpf.Models.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Geburtsjahr")
                        .HasColumnType("integer");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OrtId")
                        .HasColumnType("integer");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrtId");

                    b.ToTable("Autoren", (string)null);
                });

            modelBuilder.Entity("BibWpf.Models.Buch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Erscheinungsjahr")
                        .HasColumnType("integer");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("OrtId")
                        .HasColumnType("integer");

                    b.Property<int?>("Seiten")
                        .HasColumnType("integer");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("VerlagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("OrtId");

                    b.HasIndex("Titel");

                    b.HasIndex("VerlagId");

                    b.ToTable("Buecher", (string)null);
                });

            modelBuilder.Entity("BibWpf.Models.Ort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Land")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Orte", (string)null);
                });

            modelBuilder.Entity("BibWpf.Models.Verlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Gruendungsjahr")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("OrtId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrtId");

                    b.ToTable("Verlage", (string)null);
                });

            modelBuilder.Entity("BibWpf.Models.Autor", b =>
                {
                    b.HasOne("BibWpf.Models.Ort", "Ort")
                        .WithMany("Autoren")
                        .HasForeignKey("OrtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ort");
                });

            modelBuilder.Entity("BibWpf.Models.Buch", b =>
                {
                    b.HasOne("BibWpf.Models.Autor", "Autor")
                        .WithMany("Buecher")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibWpf.Models.Ort", "Ort")
                        .WithMany("Buecher")
                        .HasForeignKey("OrtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BibWpf.Models.Verlag", "Verlag")
                        .WithMany("Buecher")
                        .HasForeignKey("VerlagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Ort");

                    b.Navigation("Verlag");
                });

            modelBuilder.Entity("BibWpf.Models.Verlag", b =>
                {
                    b.HasOne("BibWpf.Models.Ort", "Ort")
                        .WithMany("Verlage")
                        .HasForeignKey("OrtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ort");
                });

            modelBuilder.Entity("BibWpf.Models.Autor", b =>
                {
                    b.Navigation("Buecher");
                });

            modelBuilder.Entity("BibWpf.Models.Ort", b =>
                {
                    b.Navigation("Autoren");

                    b.Navigation("Buecher");

                    b.Navigation("Verlage");
                });

            modelBuilder.Entity("BibWpf.Models.Verlag", b =>
                {
                    b.Navigation("Buecher");
                });
#pragma warning restore 612, 618
        }
    }
}
